### ISSUE TITLE
Theme of this project

### ISSUE THREAD

**Issue by baborok** [ShengrenHou/transformer-fault-cluster-using-K-means-#1]
Hello! Is this repo linked to thesis or some papers ?

**Comment by EnergyQuantResearch** [comment]
No. I did this for my friend who investigate it. This is a part of her PhD thesis

**Comment by baborok** [comment]
Can you link or publish this thesis ? Or is it still in progress  ?

**Comment by EnergyQuantResearch** [comment]
> Can you link or publish this thesis ? Or is it still in progress ?

It is still in progress. But you can star the project, if she finish it, I will do

**Comment by baborok** [comment]
Thanks! Will be waiting then.
